// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckTransaction(arg1:string):Promise<boolean>;

export function PrintLog(arg1:string):Promise<void>;

export function QRpopup():Promise<string>;

export function StartSession():Promise<void>;

export function VoucherPopup():Promise<boolean>;
