// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PrintLog(arg1:string):Promise<void>;

export function QRpopup():Promise<string>;

export function VoucherPopup():Promise<void>;
