// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PrintLog(arg1) {
  return window['go']['main']['App']['PrintLog'](arg1);
}

export function QRpopup() {
  return window['go']['main']['App']['QRpopup']();
}

export function VoucherPopup() {
  return window['go']['main']['App']['VoucherPopup']();
}
