// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function QRpopup() {
  return window['go']['main']['App']['QRpopup']();
}

export function TermsPopup() {
  return window['go']['main']['App']['TermsPopup']();
}

export function VoucherPopup() {
  return window['go']['main']['App']['VoucherPopup']();
}
